-- AlterEnum
ALTER TYPE "NotificationEventType" ADD VALUE 'PROPOSAL_RESUBMISSION_REMINDER_24H';

-- AlterEnum
ALTER TYPE "NotificationEventType" ADD VALUE 'PROPOSAL_RESUBMISSION_REMINDER_1H';

-- AlterEnum
ALTER TYPE "NotificationEventType" ADD VALUE 'PROPOSAL_RESUBMISSION_REMINDER_DEADLINE_PASSED';