export enum NOTIFICATION_EVENT_TYPES {
  SECURITY_PASSWORD_RESET_REQUESTED = 'SECURITY_PASSWORD_RESET_REQUESTED',
  SECURITY_PASSWORD_RESET_SUCCESS = 'SECURITY_PASSWORD_RESET_SUCCESS',
  SECURITY_PASSWORD_CHANGED = 'SECURITY_PASSWORD_CHANGED',
  SECURITY_SUSPICIOUS_RESET_ACTIVITY = 'SECURITY_SUSPICIOUS_RESET_ACTIVITY',
  SYSTEM_ACCOUNT_LOCKED = 'SYSTEM_ACCOUNT_LOCKED',
  PROFILE_NAME_CHANGED = 'PROFILE_NAME_CHANGED',
  PROFILE_AVATAR_UPDATED = 'PROFILE_AVATAR_UPDATED',

  INSTITUTION_VERIFICATION_SUBMITTED = 'INSTITUTION_VERIFICATION_SUBMITTED',
  INSTITUTION_VERIFICATION_APPROVED = 'INSTITUTION_VERIFICATION_APPROVED',
  INSTITUTION_VERIFICATION_REJECTED = 'INSTITUTION_VERIFICATION_REJECTED',

  INSTITUTION_ADDRESS_UPDATED = 'INSTITUTION_ADDRESS_UPDATED',
}

export enum NOTIFICATION_SEVERITIES {
  INFO = 'INFO',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum NOTIFICATION_STATUSES {
  UNREAD = 'UNREAD',
  READ = 'READ',
}
