export enum NOTIFICATION_EVENT_TYPES {
  SECURITY_PASSWORD_RESET_REQUESTED = 'SECURITY_PASSWORD_RESET_REQUESTED',
  SECURITY_PASSWORD_RESET_SUCCESS = 'SECURITY_PASSWORD_RESET_SUCCESS',
  SECURITY_PASSWORD_CHANGED = 'SECURITY_PASSWORD_CHANGED',
  SECURITY_SUSPICIOUS_RESET_ACTIVITY = 'SECURITY_SUSPICIOUS_RESET_ACTIVITY',
  SYSTEM_ACCOUNT_LOCKED = 'SYSTEM_ACCOUNT_LOCKED',
  PROFILE_NAME_CHANGED = 'PROFILE_NAME_CHANGED',
  PROFILE_AVATAR_UPDATED = 'PROFILE_AVATAR_UPDATED',

  DEPARTMENT_GROUP_SIZE_UPDATED = 'DEPARTMENT_GROUP_SIZE_UPDATED',

  MILESTONE_TEMPLATE_CREATED = 'MILESTONE_TEMPLATE_CREATED',

  DEPARTMENT_DOCUMENT_TEMPLATE_CREATED = 'DEPARTMENT_DOCUMENT_TEMPLATE_CREATED',

  DEPARTMENT_DOCUMENT_TEMPLATE_UPDATED = 'DEPARTMENT_DOCUMENT_TEMPLATE_UPDATED',
  DEPARTMENT_DOCUMENT_TEMPLATE_DELETED = 'DEPARTMENT_DOCUMENT_TEMPLATE_DELETED',

  INSTITUTION_VERIFICATION_SUBMITTED = 'INSTITUTION_VERIFICATION_SUBMITTED',
  INSTITUTION_VERIFICATION_APPROVED = 'INSTITUTION_VERIFICATION_APPROVED',
  INSTITUTION_VERIFICATION_REJECTED = 'INSTITUTION_VERIFICATION_REJECTED',

  INSTITUTION_ADDRESS_UPDATED = 'INSTITUTION_ADDRESS_UPDATED',

  INSTITUTION_LOGO_UPDATED = 'INSTITUTION_LOGO_UPDATED',

  INVITATION_SENT = 'INVITATION_SENT',
  INVITATIONS_BULK_SENT = 'INVITATIONS_BULK_SENT',

  GROUP_LEADER_REQUEST_SUBMITTED = 'GROUP_LEADER_REQUEST_SUBMITTED',
  GROUP_LEADER_REQUEST_APPROVED = 'GROUP_LEADER_REQUEST_APPROVED',
  GROUP_LEADER_REQUEST_REJECTED = 'GROUP_LEADER_REQUEST_REJECTED',

  PROPOSAL_SUBMITTED = 'PROPOSAL_SUBMITTED',
  PROPOSAL_APPROVED = 'PROPOSAL_APPROVED',
  PROPOSAL_REJECTED = 'PROPOSAL_REJECTED',
  PROPOSAL_FEEDBACK_ADDED = 'PROPOSAL_FEEDBACK_ADDED',
  PROPOSAL_RESUBMISSION_REMINDER_CREATED = 'PROPOSAL_RESUBMISSION_REMINDER_CREATED',
  PROPOSAL_RESUBMISSION_REMINDER_24H = 'PROPOSAL_RESUBMISSION_REMINDER_24H',
  PROPOSAL_RESUBMISSION_REMINDER_1H = 'PROPOSAL_RESUBMISSION_REMINDER_1H',
  PROPOSAL_RESUBMISSION_REMINDER_DEADLINE_PASSED = 'PROPOSAL_RESUBMISSION_REMINDER_DEADLINE_PASSED',

  PROJECT_ADVISOR_ASSIGNED = 'PROJECT_ADVISOR_ASSIGNED',

  DEPARTMENT_ANNOUNCEMENT_CREATED = 'DEPARTMENT_ANNOUNCEMENT_CREATED',
  DEPARTMENT_ANNOUNCEMENT_DEADLINE_24H = 'DEPARTMENT_ANNOUNCEMENT_DEADLINE_24H',
  DEPARTMENT_ANNOUNCEMENT_DEADLINE_1H = 'DEPARTMENT_ANNOUNCEMENT_DEADLINE_1H',
  DEPARTMENT_ANNOUNCEMENT_DEADLINE_PASSED = 'DEPARTMENT_ANNOUNCEMENT_DEADLINE_PASSED',

  PROJECT_GROUP_TASK_DUE_DATE_24H = 'PROJECT_GROUP_TASK_DUE_DATE_24H',
}

export enum NOTIFICATION_SEVERITIES {
  INFO = 'INFO',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum NOTIFICATION_STATUSES {
  UNREAD = 'UNREAD',
  READ = 'READ',
}
